package agh.ics.oop.constants;

import java.util.HashMap;
import java.util.Map;

public enum ParameterType {
    ANIMAL_INITIAL_ENERGY,
    ANIMAL_CONSUMPTION_ENERGY,
    ANIMAL_MIN_COPULATION_ENERGY,
    ANIMAL_ENERGY_USED_ON_COPULATION,
    ANIMAL_ENERGY_USED_ON_MOVE,
    ANIMAL_GENOME_LENGTH,
    ANIMAL_BEHAVIOR_VARIANT,
    GENOME_MIN_MUTATION_NUMBER,
    GENOME_MAX_MUTATION_NUMBER,
    GENOME_MUTATION_VARIANT,
    MAP_HEIGHT,
    MAP_WIDTH,
    MAP_VARIANT,
    MAP_JUNGLE_WIDTH,
    MAP_INITIAL_ANIMAL_NUMBER,
    MAP_INITIAL_GRASS_NUMBER,
    MAP_GRASS_GROWTH_VARIANT,
    MAP_DAILY_GRASS_GROWTH,
    SIMULATION_REFRESH_RATE;

    public String toString() {
        return switch (this) {
            case ANIMAL_INITIAL_ENERGY -> "ANIMAL_INITIAL_ENERGY";
            case ANIMAL_CONSUMPTION_ENERGY -> "ANIMAL_CONSUMPTION_ENERGY";
            case ANIMAL_MIN_COPULATION_ENERGY -> "ANIMAL_MIN_COPULATION_ENERGY";
            case ANIMAL_ENERGY_USED_ON_COPULATION -> "ANIMAL_ENERGY_USED_ON_COPULATION";
            case ANIMAL_ENERGY_USED_ON_MOVE -> "ANIMAL_ENERGY_USED_ON_MOVE";
            case ANIMAL_GENOME_LENGTH -> "ANIMAL_GENOME_LENGTH";
            case ANIMAL_BEHAVIOR_VARIANT -> "ANIMAL_BEHAVIOR_VARIANT";
            case GENOME_MIN_MUTATION_NUMBER -> "GENOME_MIN_MUTATION_NUMBER";
            case GENOME_MAX_MUTATION_NUMBER -> "GENOME_MAX_MUTATION_NUMBER";
            case GENOME_MUTATION_VARIANT -> "GENOME_MUTATION_VARIANT";
            case MAP_HEIGHT -> "MAP_HEIGHT";
            case MAP_WIDTH -> "MAP_WIDTH";
            case MAP_VARIANT -> "MAP_VARIANT";
            case MAP_JUNGLE_WIDTH -> "MAP_JUNGLE_WIDTH";
            case MAP_INITIAL_ANIMAL_NUMBER -> "MAP_INITIAL_ANIMAL_NUMBER";
            case MAP_INITIAL_GRASS_NUMBER -> "MAP_INITIAL_GRASS_NUMBER";
            case MAP_GRASS_GROWTH_VARIANT -> "MAP_GRASS_GROWTH_VARIANT";
            case MAP_DAILY_GRASS_GROWTH -> "MAP_DAILY_GRASS_GROWTH";
            case SIMULATION_REFRESH_RATE -> "SIMULATION_REFRESH_RATE";
        };
    }

    public Object parse(int value){
        return switch (this) {
            case ANIMAL_INITIAL_ENERGY, ANIMAL_CONSUMPTION_ENERGY, ANIMAL_MIN_COPULATION_ENERGY, ANIMAL_ENERGY_USED_ON_COPULATION,
                    ANIMAL_ENERGY_USED_ON_MOVE, ANIMAL_GENOME_LENGTH, GENOME_MIN_MUTATION_NUMBER, GENOME_MAX_MUTATION_NUMBER,
                    MAP_HEIGHT, MAP_WIDTH, MAP_INITIAL_ANIMAL_NUMBER, MAP_INITIAL_GRASS_NUMBER, MAP_DAILY_GRASS_GROWTH,
                    SIMULATION_REFRESH_RATE, MAP_JUNGLE_WIDTH -> value;
            case MAP_VARIANT -> MapVariant.parse(value);
            case MAP_GRASS_GROWTH_VARIANT -> GrassGrowthVariant.parse(value);
            case GENOME_MUTATION_VARIANT -> AnimalMutationVariant.parse(value);
            case ANIMAL_BEHAVIOR_VARIANT -> AnimalBehaviorVariant.parse(value);
        };
    }

}
